baseurl: ""
url: "https://qxz6b1w7-5050.use.devtunnels.ms/" # Optional, helps if using absolute URLs
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
exclude:
  - node_modules
  - Gemfile.lock
  - README.md
  - .jekyll-cache
  - gen.py
  - repost/template/